[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    "RUSTSEC-2021-0145" # from criterion, used only for benchmarking
]

[licenses]
version = 2
allow = [
    "MIT",
    "Unicode-DFS-2016",
    "Apache-2.0",
    "Zlib",
    "ISC",
    "BSD-3-Clause"
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
